color0 #303340
color1 #d0679d
color2 #5fb3a1
color3 #fffac2
color4 #91b4d5
color5 #f087bd
color6 #89ddff
color7 #a6accd
color8 #767c9d
color9 #d0679d
color10 #5de4c7
color11 #fffac2
color12 #add7ff
color13 #f087bd
color14 #5de4c7
color15 #e4f0fb

cursor                #a6accd
cursor_text_color     #1b1e28
background            #1b1e28
foreground            #a6accd
selection_foreground  #e4f0fb
selection_background  #717cb4
active_border_color   #5de4c7
inactive_border_color #303340
url_color             #5de4c7

active_tab_foreground   #1b1e28
active_tab_background   #5de4c7
inactive_tab_foreground #767c9d
inactive_tab_background #303340
cursor_trail_color      #767c9d
