font_family      Noto Nerd Font
bold_font        auto
italic_font      auto
font_size        10.0

# [CURSOR]
# cursor           #88c0d0
cursor_shape     block
cursor_blink_interval 0

mouse_hide_wait  3.0
# url_color        #81a1c1
url_style        curly

# [SCROLL]
scrollback_lines 10000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER

# [TABS]
tab_bar_edge     top
tab_bar_style    powerline
tab_powerline_style slanted
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# [MISC]
bell_on_errors off

# [KEYBINDS]
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map ctrl+shift+enter new_window
map ctrl+shift+q close_window
map ctrl+shift+plus increase_font_size
map ctrl+shift+minus decrease_font_size
map ctrl+shift+0 reset_font_size
map ctrl+shift+f>scrollback_lines 1000

# BEGIN_KITTY_THEME
# Dark Pastel
include poimandres.conf
# END_KITTY_THEME

background_opacity 0.6
enable_background_blur yes
background_blur 1
allow_remote_control true
dynamic_background_opacity true
